/// <reference types="node" />
// Writes src/lib/time-zone-catalog.ts, the zones the タイムゾーン sheet can search: every zone in the system's `zone.tab`
// (IANA's canonical zones, one country each) with its country's Japanese name, and the older names ICU still answers for some
// of them (Asia/Calcutta for Asia/Kolkata). Hermes has neither `Intl.supportedValuesOf` nor a reliable `Intl.DisplayNames`,
// so the app bundles the result. Rerun after a tzdata update: pnpm --filter @switch-time/app zones:generate
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const zoneTab = process.argv[2] ?? '/usr/share/zoneinfo/zone.tab'
const out = join(import.meta.dirname, '../src/lib/time-zone-catalog.ts')
const countryName = new Intl.DisplayNames('ja', { type: 'region' })

// zone.tab rows: country code, coordinates, zone id, comment; `#` lines are comments.
const rows = readFileSync(zoneTab, 'utf8')
  .split('\n')
  .filter((line) => line !== '' && !line.startsWith('#'))
  .map((line) => line.split('\t'))
  .map(([code = '', , id = '']) => [id, countryName.of(code) ?? code] as const)
  .sort(([a], [b]) => a.localeCompare(b))

// ICU answers some zones by an older name (resolvedOptions() of Asia/Kolkata is Asia/Calcutta); a device may report either.
const aliases = rows.flatMap(([id]) => {
  const icuName = new Intl.DateTimeFormat('en-US', {
    timeZone: id,
  }).resolvedOptions().timeZone
  return icuName === id ? [] : [[icuName, id] as const]
})

const quote = (text: string) => `'${text.replaceAll("'", "\\'")}'`
const source = `// Generated by scripts/generate-time-zones.mts from zone.tab (IANA tzdata) and Intl.DisplayNames('ja'); do not edit by hand.

/** Every canonical IANA zone with its country's Japanese name, sorted by id: what the タイムゾーン sheet searches. */
export const CATALOG_ZONES: readonly (readonly [id: string, country: string])[] = [
${rows.map(([id, country]) => `  [${quote(id)}, ${quote(country)}],`).join('\n')}
]

/** Older names a device can report for a catalog zone (ICU keeps Asia/Calcutta for Asia/Kolkata), mapped to the catalog's id. */
export const ZONE_ALIASES: Readonly<Record<string, string>> = {
${aliases.map(([alias, id]) => `  ${quote(alias)}: ${quote(id)},`).join('\n')}
}
`
writeFileSync(out, source)
console.log(`${rows.length} zones, ${aliases.length} aliases → ${out}`)
